import mongoose, { Schema } from "mongoose";

const productSchema = new Schema({
  title: {
    type: String,
    required: true,
    index: true,
    lowercase: true,
    trim: true,
  },
  category: {
    type: String, 
    required: true,
    index: true,
    lowercase: true,
    trim: true,
  },
  shortDesc : { // Used for displaying product on Home Page
    type : String , 
    required : true,
    maxlength : 100
  },

  stock: {
    type: Number,
    required: true,
    default: 1,
    min : [0 , "Stock can never be negative"]
  },
  price: {
    type: Number,
    required: true,
    min: [1 , "Price must be atleast 1"],
  },
  description: {
    type: String,
    required: true,
    trim: true,
  },
  image: {
    url: {
      type: String,
      required: true,
    },
    public_id: {
      // this is generated by cloudinary and used to destroy the object from the cloud server of the cloudinary
      type: String,
      required: true,
    },
  },
} , {timestamps : true});


export const Product = mongoose.model("Product" , productSchema)